#spring:
#  session:
#    store-type: none
    
logging:
  level:
    com.uber.jaeger: debug
    golianekm: debug


management:
  metrics:
    use-global-registry: true
    binders:
      files:
        enabled: true
      processor:
        enabled: true    
        
    distribution:
      #percentiles-histogram:
      #  "[http.server.requests]": true
      sla:
        "[http.server.requests]": 10ms, 100ms
      #percentiles:
      #  "[http.server.requests]": 0.5, 0.75, 0.95, 0.98, 0.99, 0.999, 1.0        
    export:
      prometheus:
        enabled: true
        descriptions: false
        
        
  security:
    enabled: false

spring:
  application:
    name: spring-boot



opentracing:
        
  jaeger:  
    enabled: true
    udp-sender:
      host: 192.168.1.200
      port: 6831
    probabilistic-sampler:
      sampling-rate: 1.0
    log-spans: true
         
endpoints:
  
  metrics:
    enabled: false
  prometheus:
    
    enabled: true
    id: metrics
    sensitive: true